spring:
  application:
    name: SpringBoot253CloudConfigServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/JavaProject/JavaTestProject/SpringCloudProject24/SpringBoot253CloudConfigServer/src/main/resources/configs

server:
  port: 17080


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:19080/eureka/
  instance:
    appname: SpringBoot253CloudConfigServer
    hostname: 127.0.0.1
